"""Friendly ISCO-inspired job-market taxonomy used after collection."""

from __future__ import annotations


JOB_MARKETS: list[dict] = [
    {"market_id": "it", "name": "IT & Software", "parent_id": None, "isco": "25", "keywords": []},
    {"market_id": "it.software", "name": "Software Engineering", "parent_id": "it", "isco": "2512",
     "keywords": ["software engineer", "software developer", "backend", "frontend", "full stack", "fullstack",
                  "mobile developer", "ios", "android",
                  "computer science", "founding engineer", "forward deployed engineer", "product engineer",
                  "quality assurance", "qa engineer", "qa automation engineer", "test engineer", "test automation engineer",
                  "solutions architect", "solution architect", "solutions engineer",
                  "python developer", "python engineer", "java developer", "java engineer",
                  "web developer", "react developer", "back end developer", ".net developer",
                  "hardware engineer", "hardware technician", "firmware engineer", "firmware engineering",
                  "support engineer", "field service engineer", "design engineer", "integration engineer",
                  "application engineer", "application architect", "application developer",
                  "cloud architect", "enterprise architect", "data architect",
                  "database administrator", "system administrator", "network administrator",
                  "engineering intern", "software development", "software intern", "swe intern",
                  "it intern", "information technology intern", "technology intern", "computer science intern",
                  "application development intern", "web development intern", "developer intern",
                  "hardware engineering intern", "firmware engineering intern", "systems engineering intern",
                  "test engineering intern", "automation intern", "product engineering intern",
                  "engineering lead", "head of engineering", "principal engineer", "member of technical staff",
                  "go-to-market engineer", "information technology", "computer engineering"]},
    {"market_id": "it.data", "name": "Data, AI & Machine Learning", "parent_id": "it", "isco": "2511",
     "keywords": ["data scientist", "data science", "data analyst", "data analytics", "data engineer",
                  "machine learning", "ml engineer", "mlops", "ai engineer", "ai architect",
                  "artificial intelligence", "computer vision", "business intelligence", "llm",
                  "analytics engineer", "research scientist", "research engineer", "machine vision",
                  "ai intern", "ai development intern", "ai automation intern", "ai enablement intern",
                  "ai scientist intern", "ai research intern", "ai/ml intern", "data intern",
                  "analytics intern", "research intern", "r&d intern", "research and development intern",
                  "research assistant", "enterprise data intern", "gis intern", "loyalty analytics"]},
    {"market_id": "it.infrastructure", "name": "Cloud, DevOps & Security", "parent_id": "it", "isco": "252",
     "keywords": ["devops", "devsecops", "site reliability", "sre", "cloud engineer", "platform engineer",
                  "cybersecurity", "cyber security", "security engineer", "network engineer", "systems engineer",
                  "infrastructure engineer", "information security", "security analyst",
                  "cyber security intern", "information security intern", "security analyst intern",
                  "systems engineer intern", "system engineer"]},
    {"market_id": "it.product", "name": "Product & Technical Leadership", "parent_id": "it", "isco": "1330",
     "keywords": ["product manager", "technical product", "engineering manager", "cto", "chief technology", "vp engineering",
                  "product owner", "product management", "product development", "head of product", "chief of staff"]},

    {"market_id": "healthcare", "name": "Healthcare & Medical", "parent_id": None, "isco": "22", "keywords": []},
    {"market_id": "healthcare.clinical", "name": "Clinical Care", "parent_id": "healthcare", "isco": "22",
     "keywords": ["physician", "doctor", "nurse", "clinical", "pharmacist", "therapist", "dentist", "medical assistant",
                  "general surgery", "nephrology", "anesthesia", "anesthesiology", "anesthetist",
                  "pediatric", "pediatrics", "pediatrician", "radiology", "radiologist", "radiographer",
                  "diagnostic radiology", "interventional radiology", "interventional radiologist",
                  "ophthalmology", "urology", "urologist", "gastroenterology", "general medicine",
                  "internal medicine", "family medicine", "community medicine", "cardiology", "cardiac surgery",
                  "gynecology", "obstetrics", "dermatology", "radiation oncology", "psychiatry", "psychiatrist",
                  "pathology", "pathologist", "histopathology", "chemical pathology", "neurosurgery", "neurology",
                  "critical care", "emergency medicine", "medical officer", "pulmonology", "nursing assistant",
                  "dental assistant", "nuclear medicine", "midwife", "lab technician", "phlebotomist",
                  "thoracic surgeon", "hepato-pancreatico biliary surgeon", "head and neck surgeon",
                  "plastic & reconstructive surgeon", "orthopedic surgeon", "breast surgeon",
                  "palliative medicine", "forensic medicine", "hematology", "ot technician", "dispenser",
                  "obstetrics & gynecology", "gynecologic oncology", "surgeon", "surgery", "oncologist",
                  "oncology", "medical oncologist"]},
    {"market_id": "healthcare.life_sciences", "name": "Life Sciences & Research", "parent_id": "healthcare", "isco": "2131",
     "keywords": ["biologist", "biotech", "life sciences", "laboratory", "bioinformatics",
                  "microbiology", "biochemistry", "pharmacology", "anatomy", "physiology", "botany", "zoology"]},

    {"market_id": "engineering", "name": "Engineering & Manufacturing", "parent_id": None, "isco": "21,31", "keywords": []},
    {"market_id": "engineering.core", "name": "Core Engineering", "parent_id": "engineering", "isco": "214",
     "keywords": ["mechanical engineer", "electrical engineer", "civil engineer", "chemical engineer", "aerospace engineer", "structural engineer",
                  "electrical", "mechanical", "civil", "chemical", "electronics",
                  "geotechnical", "field engineer intern", "project engineer intern", "structural intern",
                  "environmental sciences", "environmental engineering"]},
    {"market_id": "engineering.manufacturing", "name": "Manufacturing & Quality", "parent_id": "engineering", "isco": "31",
     "keywords": ["manufacturing", "production engineer", "quality engineer", "process engineer", "industrial engineer", "maintenance engineer"]},
    {"market_id": "engineering.trades", "name": "Skilled Trades & Maintenance", "parent_id": "engineering", "isco": "71,72",
     "keywords": ["electrician", "auto electrician", "plumber", "carpenter", "painter", "welder", "mason",
                  "fitter", "ac technician", "draftsman", "mechanic", "vehicle mechanic", "hvac",
                  "quantity surveyor", "generator operator"]},

    {"market_id": "business", "name": "Business & Finance", "parent_id": None, "isco": "24", "keywords": []},
    {"market_id": "business.finance", "name": "Finance, Accounting & Quant", "parent_id": "business", "isco": "241",
     "keywords": ["accountant", "finance", "financial analyst", "investment", "quantitative", "quant trader", "auditor", "controller",
                  "accounting manager", "tax manager", "chief financial officer", "bookkeeper",
                  "accounts receivable specialist", "accounts officer", "branch manager"]},
    {"market_id": "business.sales", "name": "Sales & Marketing", "parent_id": "business", "isco": "243",
     "keywords": ["sales", "account executive", "business development", "marketing", "growth manager", "brand manager",
                  "account manager", "technical account manager", "key account manager", "strategic account manager",
                  "senior account manager", "client success manager", "customer service representative",
                  "customer service agent", "customer experience manager", "paid media specialist", "seo specialist"]},
    {"market_id": "business.people", "name": "People, HR & Recruiting", "parent_id": "business", "isco": "2423",
     "keywords": ["human resources", "people operations", "recruiter", "talent acquisition", "hr manager",
                  "hr business partner", "hr officer", "hr generalist", "technical recruiter"]},
    {"market_id": "business.consulting", "name": "Consulting & Analysis", "parent_id": "business", "isco": "2421",
     "keywords": ["consultant", "business analyst", "management consultant", "strategy analyst", "operations analyst",
                  "project coordinator", "operations associate", "program analyst", "implementation manager",
                  "service delivery manager", "proposal manager", "business administration", "management sciences"]},

    {"market_id": "operations", "name": "Operations", "parent_id": None, "isco": "13,33,43", "keywords": []},
    {"market_id": "operations.supply", "name": "Supply Chain & Logistics", "parent_id": "operations", "isco": "1324",
     "keywords": ["supply chain", "logistics", "procurement", "warehouse", "transportation", "inventory"]},
    {"market_id": "operations.service", "name": "Customer & Business Operations", "parent_id": "operations", "isco": "33,42",
     "keywords": ["customer success", "customer support", "operations manager", "program manager", "project manager", "office manager",
                  "executive assistant", "administrative assistant", "virtual assistant", "receptionist",
                  "office assistant", "admin officer"]},
    {"market_id": "operations.support_services", "name": "Support & Facilities Staff", "parent_id": "operations", "isco": "91,93,94",
     "keywords": ["naib qasid", "chowkidar", "mali", "sweeper", "sanitary worker", "office boy", "aya",
                  "driver", "drivers", "security guard", "security guards", "security supervisor",
                  "cook", "waiter", "storeman", "store keeper", "assistant store keeper",
                  "computer operator", "data entry operator", "dispatch rider", "cctv operator",
                  "fireman", "sewerman", "clerk", "lower division clerk"]},

    {"market_id": "creative", "name": "Creative", "parent_id": None, "isco": "26", "keywords": []},
    {"market_id": "creative.design", "name": "Design & User Experience", "parent_id": "creative", "isco": "2166",
     "keywords": ["designer", "ux", "ui", "user experience", "product design", "graphic design"]},
    {"market_id": "creative.content", "name": "Content, Media & Communications", "parent_id": "creative", "isco": "264",
     "keywords": ["writer", "editor", "content", "communications", "journalist", "social media", "copywriter"]},

    {"market_id": "education", "name": "Education", "parent_id": None, "isco": "23", "keywords": []},
    {"market_id": "education.teaching", "name": "Teaching & Learning", "parent_id": "education", "isco": "23",
     "keywords": ["teacher", "professor", "instructor", "lecturer", "tutor", "curriculum", "learning designer",
                  "english", "urdu", "mathematics", "maths", "chemistry", "physics", "biology", "science",
                  "statistics", "economics", "commerce", "geography", "history", "sociology",
                  "islamic studies", "islamiyat", "islamiat", "pakistan studies", "principal", "librarian"]},

    {"market_id": "legal", "name": "Legal", "parent_id": None, "isco": "261", "keywords": []},
    {"market_id": "legal.practice", "name": "Legal Practice & Compliance", "parent_id": "legal", "isco": "261",
     "keywords": ["lawyer", "attorney", "legal counsel", "paralegal", "compliance", "legal assistant", "privacy counsel"]},
]

MARKETS_BY_ID = {market["market_id"]: market for market in JOB_MARKETS}
LEAF_MARKETS = [market for market in JOB_MARKETS if market["keywords"]]
